name: multifast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  collection: ^1.19.0
  dio: ^5.7.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  fpdart: ^1.1.0
  get_it: ^8.0.3
  go_router: ^14.6.3
  grpc: ^4.0.1
  intl: ^0.20.2
  meta: ^1.15.0
  mobile_scanner: ^6.0.3
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.1
  printing: ^5.12.0
  protobuf: ^3.1.0
  provider: ^6.0.5
  responsive_framework: ^1.5.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  table_calendar: ^3.2.0
  talker: ^4.5.2
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  protoc_plugin: ^21.1.2

flutter:
  assets:
    - assets/pngs/
    - assets/pngs/icons/
    - assets/pngs/options/
    - assets/pngs/core/
  fonts:
    - family: KoHo
      fonts:
        - asset: assets/fonts/KoHo-Regular.ttf
        - asset: assets/fonts/KoHo-Italic.ttf
          style: italic
        - asset: assets/fonts/KoHo-Medium.ttf
          weight: 500
        - asset: assets/fonts/KoHo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KoHo-Bold.ttf
          weight: 700
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pngs/core/logo_x513.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets//pngs/core/logo_icon_x228.png"

targets:
  $default:
    sources:
      - lib/**
      - protos/**
    builders:
      grpc:
        enabled: true