// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_iS7dAfW0A1NBmAfxE4rNBd-vm0zYYyA',
    appId: '1:495534798316:web:59822152f83e3e909e3cc9',
    messagingSenderId: '495534798316',
    projectId: 'fastapi-c550f',
    authDomain: 'fastapi-c550f.firebaseapp.com',
    storageBucket: 'fastapi-c550f.firebasestorage.app',
    measurementId: 'G-3Q150453XX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvCA4b4EbBNB2qwo8-08fhEHxj8e0NiQk',
    appId: '1:495534798316:ios:16208c19515a69219e3cc9',
    messagingSenderId: '495534798316',
    projectId: 'fastapi-c550f',
    storageBucket: 'fastapi-c550f.firebasestorage.app',
    iosBundleId: 'com.example.multifast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvCA4b4EbBNB2qwo8-08fhEHxj8e0NiQk',
    appId: '1:495534798316:ios:16208c19515a69219e3cc9',
    messagingSenderId: '495534798316',
    projectId: 'fastapi-c550f',
    storageBucket: 'fastapi-c550f.firebasestorage.app',
    iosBundleId: 'com.example.multifast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_iS7dAfW0A1NBmAfxE4rNBd-vm0zYYyA',
    appId: '1:495534798316:web:2982900d9aa5f6409e3cc9',
    messagingSenderId: '495534798316',
    projectId: 'fastapi-c550f',
    authDomain: 'fastapi-c550f.firebaseapp.com',
    storageBucket: 'fastapi-c550f.firebasestorage.app',
    measurementId: 'G-1R975NVVPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyQMgeJbPygl-TH0cyFvRQnQNuhtwzP_c',
    appId: '1:495534798316:android:0d62eac28e5e15269e3cc9',
    messagingSenderId: '495534798316',
    projectId: 'fastapi-c550f',
    storageBucket: 'fastapi-c550f.firebasestorage.app',
  );

}